# Site settings
title: "PepperBoi"
email: pepper_boi@icloud.com
description: "Hobbiest game developer using Godot"
baseurl: ""
url: "http://pepper-boi.github.io/"
title_description: "A dark blog theme for Jekyll focusing on a clear reading experience. Large text and a narrow body makes carte noire a gorgeous read. With excellent code snippet support and integrated tools such as AddThis and Disqus giving your Jekyll blog all the functionality your users expect."
title_image: "https://s.gravatar.com/avatar/cde0e4582597413d1e2c98b83f2e3c71?s=80"
google_analytics: "UA-20365477-4"
disqus_account: cartenoire
github_repository: https://github.com/pepper-boi/pepper-boi.github.io
addthis_id: ra-513c6fa83da6ec67
post_limit: 5

# Social usernames/URLs
twitter_username: 
github_username: pepper-boi
instagram_username: 
reddit_username: 
linkedin_link:
google_plus_link:
stackoverflow_link:
xing_link:
facebook_link:

# Footer
footer_left: "Made using <a href=\"https://github.com/jacobtomlinson/carte-noire\">Carte Noire</a>, <a href=\"https://https://jekyllrb.com\">Jekyll</a>, and <a href=\"https://https://jekyllrb.com\">Github Pages</a>,"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
