# Site settings
title: "PepperBoi"
email: pepper_boi@icloud.com
description: "Hobbiest game developer using Godot"
baseurl: ""
url: "http://pepper-boi.github.io/"
title_description: "Hobbiest game developer using Godot. I've made over 20 games, mostly for game jams. This website is for showing my portfolio and my blog."
title_image: "https://s.gravatar.com/avatar/cde0e4582597413d1e2c98b83f2e3c71?s=80"
google_analytics: "UA-20365477-4"
disqus_account: cartenoire
github_repository: https://github.com/pepper-boi/pepper-boi.github.io
addthis_id: ra-513c6fa83da6ec67
post_limit: 5

# Social usernames/URLs
github_username: pepper-boi
itch_username: pepperboi

# Footer
footer_left: "Made using <a href=\"https://github.com/jacobtomlinson/carte-noire\">Carte Noire</a>, <a href=\"https://jekyllrb.com\">Jekyll</a>, and <a href=\"https://pages.github.com/\">Github Pages</a>."

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
